name: build manylinux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Initialize submodule
      run: git submodule update --init --recursive
    - name: Build in manylinux container
      run: docker run --rm -v `pwd`:/repo --rm safijari/manylinux_2_28-x64 /repo/build.sh manylinux_2_28_x86_64
    - name: Build in manylinux container legacy
      run: docker run --rm -v `pwd`:/repo --rm safijari/manylinux2014 /repo/build.sh manylinux2014_x86_64
    - name: Tar up artifacts
      run: tar -czf dist.tar.gz dist/
    - uses: actions/upload-artifact@main
      with:
        name: dist
        path: dist/
